import '../input/vr_input_event_bus.dart';
import 'vr_pairing_payload.dart';

/// Transport contract for direct sockets, Bluetooth LE, or Wi-Fi Direct.
abstract interface class VrTransport {
  /// Connects using an invitation generated by the parent visor.
  Future<void> connect(VrPairingPayload payload);

  /// Remote input events received from the connected device.
  Stream<VrInputEvent> get onEvent;

  /// Sends one canonical VR input event to the peer.
  Future<void> sendEvent(VrInputEvent event);

  /// Closes the current connection and releases transport resources.
  Future<void> disconnect();
}
