import 'package:vector_math/vector_math.dart';

import '../core/math/aabb.dart';

/// Raw vertex data for a 3D geometry.
class Geometry {
  /// Vertex positions (3 floats per vertex).
  final List<Vector3> vertices;

  /// Vertex normals (3 floats per vertex).
  final List<Vector3> normals;

  /// UV coordinates (2 floats per vertex).
  final List<Vector2> uvs;

  /// Triangle indices (3 per triangle).
  final List<int> indices;

  Aabb? _cachedAabb;

  Geometry({
    required this.vertices,
    List<Vector3>? normals,
    List<Vector2>? uvs,
    required this.indices,
  }) : normals = normals ?? _computeNormals(vertices, indices),
       uvs = uvs ?? List.filled(vertices.length, Vector2.zero());

  int get vertexCount => vertices.length;
  int get triangleCount => indices.length ~/ 3;

  Aabb get aabb {
    if (_cachedAabb != null) return _cachedAabb!;
    final box = Aabb();
    for (final v in vertices) {
      box.expandToInclude(v);
    }
    _cachedAabb = box;
    return box;
  }

  /// Computes face normals and averages them per vertex.
  static List<Vector3> _computeNormals(
    List<Vector3> vertices,
    List<int> indices,
  ) {
    final normals = List.generate(vertices.length, (_) => Vector3.zero());

    for (var i = 0; i < indices.length; i += 3) {
      final a = vertices[indices[i]];
      final b = vertices[indices[i + 1]];
      final c = vertices[indices[i + 2]];

      final edge1 = b - a;
      final edge2 = c - a;
      final faceNormal = edge1.cross(edge2)..normalize();

      normals[indices[i]] += faceNormal;
      normals[indices[i + 1]] += faceNormal;
      normals[indices[i + 2]] += faceNormal;
    }

    for (final n in normals) {
      if (n.length > 0) n.normalize();
    }

    return normals;
  }
}

/// A 3D geometry generated by displacing a grid mesh using a depth map list.
class DepthDisplacedGeometry extends Geometry {
  final int widthSegments;
  final int heightSegments;
  final double width;
  final double height;
  final List<double> depthMap;
  final double maxDisplacement;

  DepthDisplacedGeometry({
    required this.widthSegments,
    required this.heightSegments,
    required this.width,
    required this.height,
    required this.depthMap,
    this.maxDisplacement = 1.0,
  }) : super(
         vertices: _buildVertices(widthSegments, heightSegments, width, height, depthMap, maxDisplacement),
         indices: _buildIndices(widthSegments, heightSegments),
       );

  static List<Vector3> _buildVertices(
    int wSegs,
    int hSegs,
    double w,
    double h,
    List<double> depths,
    double maxDisp,
  ) {
    final verts = <Vector3>[];
    for (var y = 0; y <= hSegs; y++) {
      final v = y / hSegs;
      final posY = (v - 0.5) * h;
      for (var x = 0; x <= wSegs; x++) {
        final u = x / wSegs;
        final posX = (u - 0.5) * w;
        
        final idx = y * (wSegs + 1) + x;
        final depth = idx < depths.length ? depths[idx] : 0.0;
        final posZ = depth * maxDisp; // Offset along depth axis
        
        verts.add(Vector3(posX, posY, posZ));
      }
    }
    return verts;
  }

  static List<int> _buildIndices(int wSegs, int hSegs) {
    final indices = <int>[];
    for (var y = 0; y < hSegs; y++) {
      for (var x = 0; x < wSegs; x++) {
        final i0 = y * (wSegs + 1) + x;
        final i1 = i0 + 1;
        final i2 = (y + 1) * (wSegs + 1) + x;
        final i3 = i2 + 1;

        // Triangle 1: i0 -> i1 -> i2
        indices.addAll([i0, i1, i2]);
        // Triangle 2: i1 -> i3 -> i2
        indices.addAll([i1, i3, i2]);
      }
    }
    return indices;
  }
}
